name: HonkyTonkTankers
favicon: null
layout_spectrum: 0.99375
typography_spectrum: 0.686821874929592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b42622'
    - '#000000'
    - '#fefe00'
    - '#a3615b'
  brandStrength: 1
  lightness: 0.9859229594003409
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
